### PR TITLE
Fix a bug where background color was not rendered properly on custom fgColor

### PR DESCRIPTION
**Pull request by lucaspeferreira**

### CODE REVIEW

**Comment by lucaspeferreira** [comment]
On dark backgrounds, fgColor was not working correctly between the icon and the background of the icon itself (see example).

image

Before the fix, the icon looks like this:

image

image

After the fix, the icon looks like that:

image

image

Bug only happens in Chrome/Edge browsers. On Safari/Firefox it is working properly.

**Comment by lucaspeferreira** [comment]
I opened another one because I sent an extra commit in the last PR by accident

**Comment by couetilc** [comment]
Thank you for updating the PR, I was about to close the last one.

**Comment by lucaspeferreira** [comment]
You’re welcome! I will work from now on to support mouse hover on icons since it is a highly requested feature from what I could see.

**Comment by couetilc** [comment]
Released in https://github.com/jaketrent/react-social-icons/releases/tag/v5.10.0, thank you for contributing.

**Pull request merged**
