### PR TITLE
Adds Whatsapp support to db

### PR DESCRIPTION
**Pull request by amirc**
Took the svg from https://github.com/nygardk/react-share/blob/master/src/icons.js

### CODE REVIEW

**Comment by iMerica** [comment]
LGTM 👍

**Comment by amirc** [comment]
@iMerica So what are the next steps? (that's my first pull request to an open source)

**Comment by jaketrent** [comment]
@amirc great commit! 🥇  Thanks for adding it.  I'll release it soon.

**Comment by jaketrent** [comment]
whatsapp

I re-generated the docs site with the new icon, and for some reason, the `whatsapp` icon is showing as pinterest.  The path in `networks-db.js` is different, but this is what shows up.  Lol.  I'm not sure how the icon was sourced, @amirc .  You all right with me replacing it with a new path?

**Comment by amirc** [comment]
Sure

**Comment by jaketrent** [comment]
@amirc Alternately, you could have another shot at it.  Let me know what you'd like to do.

I'm curious if you have any insight on this or if the outcome here makes any sense to you.

**Comment by amirc** [comment]
@jaketrent I looked at it quickly and didn't find the issue. I can do it tomorrow

**Comment by jaketrent** [comment]
perfect, no rush.

**Comment by jaketrent** [comment]
@amirc I have no source in mind at the moment.  That's probably the hardest part of updating this icon set is just finding an svg that is similarly setup... or making one.

**Comment by ofirpeer** [comment]
Hey :)
Is there any update regarding the whatsapp icon?

**Comment by jaketrent** [comment]
No update on my end.  If someone would like to contribute the icon, I can review and merge.

**Pull request merged**
